<?xml version="1.0" ?>

<!DOCTYPE artists [
  <!ELEMENT artists (artist+)>
  <!ELEMENT artist (name, nationality, birthYear, deathYear, specialty, placeOfStudy)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT nationality (#PCDATA)>
  <!ELEMENT birthYear (#PCDATA)>
  <!ELEMENT deathYear (#PCDATA)>
  <!ELEMENT specialty (#PCDATA)>
  <!ELEMENT placeOfStudy (#PCDATA)>
]>

<artists>
  <artist>
    <name>Vincent van Gogh</name>
    <nationality>Dutch</nationality>
    <birthYear>1853</birthYear>
    <deathYear>1890</deathYear>
    <specialty>Post-Impressionist</specialty>
    <placeOfStudy>Académie Royale des Beaux-Arts</placeOfStudy>
  </artist>
  <artist>
    <name>Salvador Dalí</name>
    <nationality>Spanish</nationality>
    <birthYear>1904</birthYear>
    <deathYear>1989</deathYear>
    <specialty>Surrealism</specialty>
    <placeOfStudy>Real Academia de Bellas Artes de San Fernando</placeOfStudy>
  </artist>
  <artist>
    <name>Edvard Munch</name>
    <nationality>Norwegian</nationality>
    <birthYear>1863</birthYear>
    <deathYear>1944</deathYear>
    <specialty>Expressionism</specialty>
    <placeOfStudy>Royal School of Art and Design</placeOfStudy>
  </artist>
  <artist>
    <name>Claude Monet</name>
    <nationality>French</nationality>
    <birthYear>1840</birthYear>
    <deathYear>1926</deathYear>
    <specialty>Impressionism</specialty>
    <placeOfStudy>École des Beaux-Arts</placeOfStudy>
  </artist>
  <artist>
    <name>Frida Kahlo</name>
    <nationality>Mexican</nationality>
    <birthYear>1907</birthYear>
    <deathYear>1954</deathYear>
    <specialty>Surrealism</specialty>
    <placeOfStudy>Escuela Nacional de Bellas Artes</placeOfStudy>
  </artist>
</artists>
