<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Donations [
    <!ELEMENT Donations (Donation+)>
    <!ELEMENT Donation (donationID, donorID, amount, paymentDate, donationType, donationPurpose)>
    <!ELEMENT donationID (#PCDATA)>
    <!ELEMENT donorID (#PCDATA)>
    <!ELEMENT amount (#PCDATA)>
    <!ATTLIST amount currency CDATA #REQUIRED>
    <!ELEMENT paymentDate (#PCDATA)>
    <!ELEMENT donationType (#PCDATA)>
    <!ELEMENT donationPurpose (#PCDATA)>
]>

<Donations>
    <Donation>
        <donationID>D001</donationID>
        <donorID>USER001</donorID>
        <amount currency="EUR">100.00</amount>
        <paymentDate>2023-11-14</paymentDate>
        <donationType>Individual</donationType>
        <donationPurpose>Exhibition Support</donationPurpose>
    </Donation>
    <Donation>
        <donationID>D002</donationID>
        <donorID>USER002</donorID>
        <amount currency="USD">250.00</amount>
        <paymentDate>2023-11-15</paymentDate>
        <donationType>Corporate</donationType>
        <donationPurpose>General Fund</donationPurpose>
    </Donation>
    <Donation>
        <donationID>D003</donationID>
        <donorID>ORG001</donorID>
        <amount currency="GBP">500.00</amount>
        <paymentDate>2023-11-16</paymentDate>
        <donationType>Organization</donationType>
        <donationPurpose>Educational Programs</donationPurpose>
    </Donation>
    <Donation>
        <donationID>D004</donationID>
        <donorID>USER003</donorID>
        <amount currency="EUR">200.00</amount>
        <paymentDate>2023-11-16</paymentDate>
        <donationType>Individual</donationType>
        <donationPurpose>Special Exhibition</donationPurpose>
    </Donation>
</Donations>
