<?xml version="1.0" ?>

<!DOCTYPE museum[

<!ELEMENT museum (artwork*)>
<!ELEMENT artwork (title, artistName, submissionDate, status)>
<!ELEMENT categories (category1, category2, category3)>
<!ELEMENT title   (#PCDATA)>
<!ELEMENT artistName   (#PCDATA)>
<!ELEMENT submissionDate  (#PCDATA)>
<!ELEMENT status  (#PCDATA)>
<!ELEMENT category1  (#PCDATA)>
<!ELEMENT category2  (#PCDATA)>
<!ELEMENT category3  (#PCDATA)>
<!ELEMENT description  (#PCDATA)>

<!ATTLIST artwork artworkID CDATA #IMPLIED>
]>

<museum>

	<artwork artworkID="1457">
		<title>Mona Lisa</title>
		<artistName>Leonardo Da Vinci</artistName>
		<submissionDate>11/12/2023</submissionDate>
		<status>Displayed</status>
		<categories>
			<category1>Renaissance</category1>
			<category2>Portrait</category2>
			<category3>Iconic</category3>
		</categories>
		<description>
			A masterpiece by Leonardo da Vinci, celebrated for its mysterious expression and revolutionary use of light and shadow through sfumato.
		</description>
	</artwork>

    	<artwork artworkID="1458">
		<title>Girl with a Pearl Earring</title>
		<artistName>Johannes Vermeer</artistName>
		<submissionDate>01/07/2023</submissionDate>
		<status>Not Displayed</status>
		<categories>
			<category1>Baroque</category1>
			<category2>Portrait</category2>
			<category3>Light and Shadow</category3>
		</categories>
		<description>
			Known as the "Mona Lisa of the North," this painting captures a young woman in a strikingly realistic and luminous portrayal.
		</description>
	</artwork>

	<artwork artworkID="1459">
		<title>The Birth of Venus</title>
		<artistName>Sandro Botticelli</artistName>
		<submissionDate>27/05/2023</submissionDate>
		<status>Displayed</status>
		<categories>
			<category1>Renaissance</category1>
			<category2>Mythology</category2>
			<category3>Iconic</category3>
		</categories>
		<description>
			This mythological depiction of Venus emerging from the sea is celebrated for its elegance and symbolic representation of beauty.
		</description>
	</artwork>

	<artwork artworkID="1460">
		<title>The Kiss</title>
		<artistName>Gustav Klimt</artistName>
		<submissionDate>12/03/2023</submissionDate>
		<status>Displayed</status>
		<categories>
			<category1>Modern Art</category1>
			<category2>Dramatic</category2>
			<category3></category3>
		</categories>
		<description>
			A romantic and decorative painting by Gustav Klimt, notable for its intricate use of gold leaf and abstracted patterns.
		</description>
	</artwork>

    	<artwork artworkID="1461">
		<title>Guernica</title>
		<artistName>Pablo Picasso</artistName>
		<submissionDate>05/10/2023</submissionDate>
		<status>Not Displayed</status>
		<categories>
			<category1>Modern Art</category1>
			<category2>Mythology</category2>
			<category3>Cubism</category3>
		</categories>
		<description>
			A powerful anti-war statement by Picasso, depicting the horrors of the Spanish Civil War through fragmented and distorted forms.
		</description>
	</artwork>

	<artwork artworkID="1462">
		<title>The Scream</title>
		<artistName>Edvard Munch</artistName>
		<submissionDate>29/09/2023</submissionDate>
		<status>Displayed</status>
		<categories>
			<category1>Baroque</category1>
			<category2>Dramatic</category2>
			<category3>Light and Shadow</category3>
		</categories>
		<description>
			One of the most recognizable works of art, this painting vividly portrays human anxiety and existential despair through bold colors and swirling forms.
		</description>
	</artwork>
    
</museum>





