<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Members [

<!ELEMENT Members (Membership+)>
<!ELEMENT Membership (price, expirationDate, visitorID, type)>
<!ELEMENT purchasePrice (#PCDATA)>
<!ELEMENT purchaseType (#PCDATA)>
<!ELEMENT purchaseDate (#PCDATA)>
<!ELEMENT expirationDate (#PCDATA)>
<!ELEMENT visitorID (#PCDATA) >
<!ELEMENT type (#PCDATA)>

<!ATTLIST Membership membershipID CDATA #REQUIRED>

]>


<Members>
	<Membership membershipID = "0001">
		<purchasePrice>500</purchasePrice>
		<purchseType>Final</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>1234</visitorID>
		<type>Patron</type>
	</Membership>

	<Membership membershipID = "0002">
		<purchasePrice>500.00</purchasePrice>
		<purchseType>Final</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>2345</visitorID>
		<type>Patron</type>
	</Membership>

	<Membership membershipID = "0003">
		<purchasePrice>1500.00</purchasePrice>
		<purchseType>Final</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>3456</visitorID>
		<type>Patron_Curator</type>
	</Membership>

	<Membership membershipID = "0004">
		<purchasePrice>1500.00</purchasePrice>
		<purchseType>Recurring</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>4567</visitorID>
		<type>Patron_Curator</type>
	</Membership>

	<Membership membershipID = "0005">
		<purchasePrice>1500.00</purchasePrice>
		<purchseType>Recurring</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>5678</visitorID>
		<type>Patron_Curator</type>
	</Membership>

	<Membership membershipID = "0006">
		<purchasePrice>5000.00</purchasePrice>
		<purchseType>Recurring</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>6789</visitorID>
		<type>Patron_Director</type>
	</Membership>

	<Membership membershipID = "0007">
		<purchasePrice>10000.00</purchasePrice>
		<purchseType>Final</purchaseType>
		<purchaseDate>2023-11-15</purchaseDate>
		<expirationDate>2024-11-15</expirationDate>
		<visitorID>7890</visitorID>
		<type>Patron_Dargan</type>
	</Membership>
</Members>
